# Generated by kpex 0.3.9
crashbackups stop
drc off
gds read /home/userdata/k67D/duynk_67d/gitnew/SAR_ADC_8BIT_IHP/gds/sar_logic.gds
load sar_logic
select top cell
flatten sar_logic_flat
load sar_logic_flat
cellname delete sar_logic -noprompt
cellname rename sar_logic_flat sar_logic
select top cell
extract path /home/userdata/k67D/duynk_67d/gitnew/SAR_ADC_8BIT_IHP/pex/output/sar_logic__sar_logic/magic_CC
extract all
ext2spice short none
ext2spice merge none
ext2spice cthresh 0.01
ext2spice subcircuits top on
ext2spice format ngspice
ext2spice -p /home/userdata/k67D/duynk_67d/gitnew/SAR_ADC_8BIT_IHP/pex/output/sar_logic__sar_logic/magic_CC -o /home/userdata/k67D/duynk_67d/gitnew/SAR_ADC_8BIT_IHP/pex/output/sar_logic__sar_logic/magic_CC/sar_logic.pex.spice
quit -noprompt