# Generated by kpex 0.3.9
crashbackups stop
drc off
gds read /home/userdata/k67D/duynk_67d/SAR_ADC_8BIT_IHP/gds/switch_array.gds
load switch_array
select top cell
flatten switch_array_flat
load switch_array_flat
cellname delete switch_array -noprompt
cellname rename switch_array_flat switch_array
select top cell
extract path /home/userdata/k67D/duynk_67d/SAR_ADC_8BIT_IHP/pex/pex_output/switch_array__switch_array/magic_RC
extract all
ext2sim labels on
ext2sim -p /home/userdata/k67D/duynk_67d/SAR_ADC_8BIT_IHP/pex/pex_output/switch_array__switch_array/magic_RC
extresist tolerance 1
extresist all
ext2spice short resistor
ext2spice merge aggressive
ext2spice cthresh 0.1
ext2spice extresist on
ext2spice subcircuits top on
ext2spice format ngspice
ext2spice -p /home/userdata/k67D/duynk_67d/SAR_ADC_8BIT_IHP/pex/pex_output/switch_array__switch_array/magic_RC -o /home/userdata/k67D/duynk_67d/SAR_ADC_8BIT_IHP/pex/pex_output/switch_array__switch_array/magic_RC/switch_array.pex.spice
quit -noprompt
