/* Generated by Yosys 0.60 (git sha1 5bafeb77dc71e054fa331ab9efa613e6fb0a1c49, clang++ 21.1.2 -fPIC -O3) */

module sg13g2_Corner(iovdd, iovss, vdd, vss);
  inout iovdd;
  wire iovdd;
  inout iovss;
  wire iovss;
  inout vdd;
  wire vdd;
  inout vss;
  wire vss;
endmodule

module sg13g2_Filler1000(iovdd, iovss, vdd, vss);
  inout iovdd;
  wire iovdd;
  inout iovss;
  wire iovss;
  inout vdd;
  wire vdd;
  inout vss;
  wire vss;
endmodule

module sg13g2_Filler10000(iovdd, iovss, vdd, vss);
  inout iovdd;
  wire iovdd;
  inout iovss;
  wire iovss;
  inout vdd;
  wire vdd;
  inout vss;
  wire vss;
endmodule

module sg13g2_Filler200(iovdd, iovss, vdd, vss);
  inout iovdd;
  wire iovdd;
  inout iovss;
  wire iovss;
  inout vdd;
  wire vdd;
  inout vss;
  wire vss;
endmodule

module sg13g2_Filler2000(iovdd, iovss, vdd, vss);
  inout iovdd;
  wire iovdd;
  inout iovss;
  wire iovss;
  inout vdd;
  wire vdd;
  inout vss;
  wire vss;
endmodule

module sg13g2_Filler400(iovdd, iovss, vdd, vss);
  inout iovdd;
  wire iovdd;
  inout iovss;
  wire iovss;
  inout vdd;
  wire vdd;
  inout vss;
  wire vss;
endmodule

module sg13g2_Filler4000(iovdd, iovss, vdd, vss);
  inout iovdd;
  wire iovdd;
  inout iovss;
  wire iovss;
  inout vdd;
  wire vdd;
  inout vss;
  wire vss;
endmodule

module sg13g2_IOPadAnalog(iovdd, iovss, vdd, vss, pad, padres);
  inout iovdd;
  wire iovdd;
  inout iovss;
  wire iovss;
  inout vdd;
  wire vdd;
  inout vss;
  wire vss;
  inout pad;
  wire pad;
  inout padres;
  wire padres;
endmodule

module sg13g2_IOPadIOVdd(iovdd, iovss, vdd, vss);
  inout iovdd;
  wire iovdd;
  inout iovss;
  wire iovss;
  inout vdd;
  wire vdd;
  inout vss;
  wire vss;
endmodule

module sg13g2_IOPadIOVss(iovdd, iovss, vdd, vss);
  inout iovdd;
  wire iovdd;
  inout iovss;
  wire iovss;
  inout vdd;
  wire vdd;
  inout vss;
  wire vss;
endmodule

module sg13g2_IOPadIn(iovdd, iovss, vdd, vss, pad, p2c);
  inout iovdd;
  wire iovdd;
  inout iovss;
  wire iovss;
  inout vdd;
  wire vdd;
  inout vss;
  wire vss;
  inout pad;
  wire pad;
  output p2c;
  wire p2c;
endmodule

module sg13g2_IOPadInOut16mA(iovdd, iovss, vdd, vss, pad, c2p, c2p_en, p2c);
  inout iovdd;
  wire iovdd;
  inout iovss;
  wire iovss;
  inout vdd;
  wire vdd;
  inout vss;
  wire vss;
  inout pad;
  wire pad;
  input c2p;
  wire c2p;
  input c2p_en;
  wire c2p_en;
  output p2c;
  wire p2c;
endmodule

module sg13g2_IOPadInOut30mA(iovdd, iovss, vdd, vss, pad, c2p, c2p_en, p2c);
  inout iovdd;
  wire iovdd;
  inout iovss;
  wire iovss;
  inout vdd;
  wire vdd;
  inout vss;
  wire vss;
  inout pad;
  wire pad;
  input c2p;
  wire c2p;
  input c2p_en;
  wire c2p_en;
  output p2c;
  wire p2c;
endmodule

module sg13g2_IOPadInOut4mA(iovdd, iovss, vdd, vss, pad, c2p, c2p_en, p2c);
  inout iovdd;
  wire iovdd;
  inout iovss;
  wire iovss;
  inout vdd;
  wire vdd;
  inout vss;
  wire vss;
  inout pad;
  wire pad;
  input c2p;
  wire c2p;
  input c2p_en;
  wire c2p_en;
  output p2c;
  wire p2c;
endmodule

module sg13g2_IOPadOut16mA(iovdd, iovss, vdd, vss, pad, c2p);
  inout iovdd;
  wire iovdd;
  inout iovss;
  wire iovss;
  inout vdd;
  wire vdd;
  inout vss;
  wire vss;
  inout pad;
  wire pad;
  input c2p;
  wire c2p;
endmodule

module sg13g2_IOPadOut30mA(iovdd, iovss, vdd, vss, pad, c2p);
  inout iovdd;
  wire iovdd;
  inout iovss;
  wire iovss;
  inout vdd;
  wire vdd;
  inout vss;
  wire vss;
  inout pad;
  wire pad;
  input c2p;
  wire c2p;
endmodule

module sg13g2_IOPadOut4mA(iovdd, iovss, vdd, vss, pad, c2p);
  inout iovdd;
  wire iovdd;
  inout iovss;
  wire iovss;
  inout vdd;
  wire vdd;
  inout vss;
  wire vss;
  inout pad;
  wire pad;
  input c2p;
  wire c2p;
endmodule

module sg13g2_IOPadTriOut16mA(iovdd, iovss, vdd, vss, pad, c2p, c2p_en);
  inout iovdd;
  wire iovdd;
  inout iovss;
  wire iovss;
  inout vdd;
  wire vdd;
  inout vss;
  wire vss;
  inout pad;
  wire pad;
  input c2p;
  wire c2p;
  input c2p_en;
  wire c2p_en;
endmodule

module sg13g2_IOPadTriOut30mA(iovdd, iovss, vdd, vss, pad, c2p, c2p_en);
  inout iovdd;
  wire iovdd;
  inout iovss;
  wire iovss;
  inout vdd;
  wire vdd;
  inout vss;
  wire vss;
  inout pad;
  wire pad;
  input c2p;
  wire c2p;
  input c2p_en;
  wire c2p_en;
endmodule

module sg13g2_IOPadTriOut4mA(iovdd, iovss, vdd, vss, pad, c2p, c2p_en);
  inout iovdd;
  wire iovdd;
  inout iovss;
  wire iovss;
  inout vdd;
  wire vdd;
  inout vss;
  wire vss;
  inout pad;
  wire pad;
  input c2p;
  wire c2p;
  input c2p_en;
  wire c2p_en;
endmodule

module sg13g2_IOPadVdd(iovdd, iovss, vdd, vss);
  inout iovdd;
  wire iovdd;
  inout iovss;
  wire iovss;
  inout vdd;
  wire vdd;
  inout vss;
  wire vss;
endmodule

module sg13g2_IOPadVss(iovdd, iovss, vdd, vss);
  inout iovdd;
  wire iovdd;
  inout iovss;
  wire iovss;
  inout vdd;
  wire vdd;
  inout vss;
  wire vss;
endmodule
