# Generated by kpex 0.3.9
crashbackups stop
drc off
gds read /home/userdata/k67D/duynk_67d/SAR_ADC_8BIT_IHP/gds/bootstrap_switch.gds
load bootstrap_switch
select top cell
flatten bootstrap_switch_flat
load bootstrap_switch_flat
cellname delete bootstrap_switch -noprompt
cellname rename bootstrap_switch_flat bootstrap_switch
select top cell
extract path /home/userdata/k67D/duynk_67d/SAR_ADC_8BIT_IHP/pex/pex_output/bootstrap_switch__bootstrap_switch/magic_RC
extract all
ext2sim labels on
ext2sim -p /home/userdata/k67D/duynk_67d/SAR_ADC_8BIT_IHP/pex/pex_output/bootstrap_switch__bootstrap_switch/magic_RC
extresist tolerance 1
extresist all
ext2spice short none
ext2spice merge none
ext2spice cthresh 0.01
ext2spice extresist on
ext2spice subcircuits top on
ext2spice format ngspice
ext2spice -p /home/userdata/k67D/duynk_67d/SAR_ADC_8BIT_IHP/pex/pex_output/bootstrap_switch__bootstrap_switch/magic_RC -o /home/userdata/k67D/duynk_67d/SAR_ADC_8BIT_IHP/pex/pex_output/bootstrap_switch__bootstrap_switch/magic_RC/bootstrap_switch.pex.spice
quit -noprompt
