# Generated by kpex 0.3.9
crashbackups stop
drc off
gds read /home/userdata/k67D/duynk_67d/SAR_ADC_8BIT_IHP/gds/inverter.gds
load inverter
select top cell
flatten inverter_flat
load inverter_flat
cellname delete inverter -noprompt
cellname rename inverter_flat inverter
select top cell
extract path /home/userdata/k67D/duynk_67d/SAR_ADC_8BIT_IHP/pex/pex_output/inverter__inverter/magic_RC
extract all
ext2sim labels on
ext2sim -p /home/userdata/k67D/duynk_67d/SAR_ADC_8BIT_IHP/pex/pex_output/inverter__inverter/magic_RC
extresist tolerance 1
extresist all
ext2spice short resistor
ext2spice merge conservative
ext2spice cthresh 0.02
ext2spice extresist on
ext2spice subcircuits top on
ext2spice format ngspice
ext2spice -p /home/userdata/k67D/duynk_67d/SAR_ADC_8BIT_IHP/pex/pex_output/inverter__inverter/magic_RC -o /home/userdata/k67D/duynk_67d/SAR_ADC_8BIT_IHP/pex/pex_output/inverter__inverter/magic_RC/inverter.pex.spice
quit -noprompt
