// Auto-generated by LibreLane
module sar_algo(
`ifdef USE_POWER_PINS
  input VDD,
  input VSS,
`endif
  input fclk_in,
  input rst,
  input Op,
  input Om,
  input En,
  input clk_algo,
  output fclk_samp,
  output fclk_comp,
  output fdac_clk,
  output[6:0] B,
  output[6:0] BN,
  output[7:0] D
);
endmodule
