# Generated by kpex 0.3.9
crashbackups stop
drc off
gds read /home/userdata/k67D/duynk_67d/SAR_ADC_8BIT_IHP/gds/T_gate.gds
load T_gate
select top cell
flatten T_gate_flat
load T_gate_flat
cellname delete T_gate -noprompt
cellname rename T_gate_flat T_gate
select top cell
extract path /home/userdata/k67D/duynk_67d/SAR_ADC_8BIT_IHP/pex/pex_output/T_gate__T_gate/magic_CC
extract all
ext2spice short resistor
ext2spice merge conservative
ext2spice cthresh 0.02
ext2spice subcircuits top on
ext2spice format ngspice
ext2spice -p /home/userdata/k67D/duynk_67d/SAR_ADC_8BIT_IHP/pex/pex_output/T_gate__T_gate/magic_CC -o /home/userdata/k67D/duynk_67d/SAR_ADC_8BIT_IHP/pex/pex_output/T_gate__T_gate/magic_CC/T_gate.pex.spice
quit -noprompt