# Generated by kpex 0.3.9
crashbackups stop
drc off
gds read /home/userdata/k67D/duynk_67d/SAR_ADC_8BIT_IHP/gds/DIFF_COMPARATOR.gds
load DIFF_COMPARATOR
select top cell
flatten DIFF_COMPARATOR_flat
load DIFF_COMPARATOR_flat
cellname delete DIFF_COMPARATOR -noprompt
cellname rename DIFF_COMPARATOR_flat DIFF_COMPARATOR
select top cell
extract path /home/userdata/k67D/duynk_67d/SAR_ADC_8BIT_IHP/pex/pex_output/DIFF_COMPARATOR__DIFF_COMPARATOR/magic_RC
extract all
ext2sim labels on
ext2sim -p /home/userdata/k67D/duynk_67d/SAR_ADC_8BIT_IHP/pex/pex_output/DIFF_COMPARATOR__DIFF_COMPARATOR/magic_RC
extresist tolerance 1
extresist all
ext2spice short none
ext2spice merge none
ext2spice cthresh 0.01
ext2spice extresist on
ext2spice subcircuits top on
ext2spice format ngspice
ext2spice -p /home/userdata/k67D/duynk_67d/SAR_ADC_8BIT_IHP/pex/pex_output/DIFF_COMPARATOR__DIFF_COMPARATOR/magic_RC -o /home/userdata/k67D/duynk_67d/SAR_ADC_8BIT_IHP/pex/pex_output/DIFF_COMPARATOR__DIFF_COMPARATOR/magic_RC/DIFF_COMPARATOR.pex.spice
quit -noprompt
