# Generated by kpex 0.3.9
crashbackups stop
drc off
gds read /home/userdata/k67D/duynk_67d/SAR_ADC_8BIT_IHP/gds/C-DAC.gds
load CDAC
select top cell
flatten CDAC_flat
load CDAC_flat
cellname delete CDAC -noprompt
cellname rename CDAC_flat CDAC
select top cell
extract path /home/userdata/k67D/duynk_67d/SAR_ADC_8BIT_IHP/pex/pex_output/C-DAC__CDAC/magic_RC
extract all
ext2sim labels on
ext2sim -p /home/userdata/k67D/duynk_67d/SAR_ADC_8BIT_IHP/pex/pex_output/C-DAC__CDAC/magic_RC
extresist tolerance 1
extresist all
ext2spice short none
ext2spice merge none
ext2spice cthresh 0.01
ext2spice extresist on
ext2spice subcircuits top on
ext2spice format ngspice
ext2spice -p /home/userdata/k67D/duynk_67d/SAR_ADC_8BIT_IHP/pex/pex_output/C-DAC__CDAC/magic_RC -o /home/userdata/k67D/duynk_67d/SAR_ADC_8BIT_IHP/pex/pex_output/C-DAC__CDAC/magic_RC/CDAC.pex.spice
quit -noprompt
